<?php

include_once "Circle.php";
class Cylinder extends Circle
{
    public $height;

    public function __construct($radius,$color,$height)
    {
        parent::__construct($radius,$color);
        $this->height = $height;
    }
    public function __toString()
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }

    public function calArea()
    {
        return parent::calArea()*($this->radius+$this->height); // TODO: Change the autogenerated stub
    }
    public function calVolume()
    {
        return parent::calArea()*$this->height;
    }
}